Repository JaManChu/frontend, pull requests merged in 2024-10, with the labels that each got.

#33 [feat] Mypage Component
  src/views/Mypage/Mypage.tsx
Labels: enhancement, design

#35 [feat] RecipePages(popular, recommend) & latest - main 컴포넌트 연결
  src/App.tsx
  src/components/Header/Header.tsx
  src/fakeData/recipeFake.ts
  src/views/Main/Main.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recipe/RecipeCard.tsx
  src/views/Recipes/Recipe/RecipeList.tsx
  src/views/Recipes/Recipe/RecipePageHeader.tsx
  src/views/Recipes/RecipeCard/RecipeCard.tsx
  src/views/Recipes/Recommend/Recommend.tsx
Labels: enhancement, design

#37 [feat] Main & RecipePages 연결
  src/assets/img/bread.png
  src/assets/img/logo.png
  src/assets/img/spoon.jpg
  src/components/Header/Header.tsx
  src/views/Main/Main.tsx
  src/views/Main/Test.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recipe/RecipeCard.tsx
  src/views/Recipes/Recipe/RecipeList.tsx
  src/views/Recipes/Recommend/Recommend.tsx
  src/views/Visited/Visited.tsx
Labels: enhancement, design

#39 [feat] GuestHome 컴포넌트
  src/views/GuestHome/GuestHome.tsx
  src/views/Onboard/Onboard.tsx
  src/views/Signup/Signup.tsx
  src/views/Signup/validation/validation.ts
Labels: enhancement, design

#41 [feat] signup 로직분리
  src/views/Signup/hooks/useModal.ts
  src/views/Signup/hooks/useSignUpForm.ts
Labels: enhancement

#43 [feat] login 커스텀훅 캡슐화
  src/views/Login/Login.tsx
  src/views/Signup/Signup.tsx
  src/views/Signup/hooks/useModal.ts
  src/views/Signup/hooks/useSignUpForm.ts
  src/views/Signup/validation/validation.ts
Labels: enhancement, design

#44 [feat] RecipeDetailComponent 생성
  src/App.tsx
  src/fakeData/recipeFake.ts
  src/views/GuestHome/GuestHome.tsx
  src/views/Main/Main.tsx
  src/views/Main/Test.tsx
  src/views/Onboard/Onboard.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/Recipe/RecipeCard.tsx
  src/views/Recipes/Recipe/RecipeMetaData.tsx
Labels: bug, enhancement, design

#48 [refactor] mypage,guesthome 커스텀훅 캡슐화
  src/views/GuestHome/GuestHome.tsx
  src/views/GuestHome/hooks/useSearchInput.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/updateForm.ts
  src/views/Mypage/hooks/useModal.ts
Labels: enhancement

#50 [fix] Vercel 배포 에러
  src/views/Comments/Comments.tsx
  src/views/Main/Main.tsx
  src/views/Rate/Rate.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recommend/Recommend.tsx
Labels: bug

#51 [feat] vercel 배포 에러 (배포 테스트)
  src/views/Comments/Comments.tsx
  src/views/Comments/ViewComments.tsx
  src/views/GuestHome/hooks/useSearchInput.ts
  src/views/Main/Main.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recommend/Recommend.tsx
Labels: bug

#54 [feat]Kakao Oauth - use library
  .gitignore
  package-lock.json
  package.json
  src/views/Login/Login.tsx
  src/views/Login/SocialKakao.tsx
  src/views/Mypage/hooks/updateForm.ts
Labels: enhancement

#56 [feat] Fix and Feat: Login and Signup Logic
  package-lock.json
  package.json
  src/hooks/useModal.ts
  src/hooks/useSearchInput.ts
  src/hooks/useUserForm.ts
  src/utils/validation/validation.ts
  src/views/Comments/ViewComments.tsx
  src/views/GuestHome/GuestHome.tsx
  src/views/Login/Login.tsx
  src/views/Login/SocialKakao.tsx
  src/views/Main/Main.tsx
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/updateForm.ts
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recommend/Recommend.tsx
  src/views/Signup/Signup.tsx
  src/views/Signup/validation/validation.ts
Labels: enhancement, design

#59 [fix]환경 변수 수정
  .gitignore
  src/hooks/useUserForm.ts
  src/views/Login/SocialKakao.tsx
  src/views/Signup/Signup.tsx
Labels: bug

#61 [fix]signup api endpoint
  src/hooks/useUserForm.ts
Labels: bug

#65 [fix]index.html - referrer
  index.html
Labels: bug

#67 [feat] SocialKakao수정
  src/views/Login/SocialKakao.tsx
Labels: enhancement

#69 [feat] SocialKakao수정
  src/views/Login/SocialKakao.tsx
Labels: enhancement

#71 [feat] SocialKakao수정
  src/views/Login/SocialKakao.tsx
Labels: enhancement

#73 [feat] 비밀번호 길이제한 유효성검사
  src/utils/validation/validation.ts
Labels: enhancement

#75 [refactor] MyPage and Onboard
  src/components/Header/Header.tsx
  src/styles/styled.ts
  src/views/Comments/Review.tsx
  src/views/Comments/ViewComments.tsx
  src/views/GuestHome/GuestHome.tsx
  src/views/Login/Login.tsx
  src/views/Login/SocialKakao.tsx
  src/views/Main/Main.tsx
  src/views/Mypage/Mypage.tsx
  src/views/Onboard/Onboard.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recipe/RecipeCard.tsx
  src/views/Recipes/Recipe/RecipeList.tsx
  src/views/Recipes/Recipe/RecipeMetaData.tsx
  src/views/Recipes/Recipe/RecipePageHeader.tsx
  src/views/Recipes/Recommend/Recommend.tsx
  src/views/Signup/Signup.tsx
  src/views/Visited/Visited.tsx
Labels: refactor, design

#77 [feat] Kakao 인가 코드 전달 로직
  src/App.tsx
  src/components/AuthKaKao.tsx
  src/views/Login/SocialKakao.tsx
Labels: bug, enhancement

#79 [feat] withAuth HOC 도입
  src/components/AuthKaKao.tsx
  src/hooks/useUserForm.ts
  src/hooks/withAuth.tsx
  src/views/Login/Login.tsx
Labels: enhancement

#82 [fix] Kakao axios logic
  src/components/AuthKaKao.tsx
Labels: wontfix

#83 Fix: Kakao OAuth - 인가코드 백엔드 redirect_uri로 변경
  src/components/AuthKaKao.tsx
  src/views/Login/SocialKakao.tsx
Labels: wontfix

#84 [refactor]Header - conditional rendering with hook
  src/App.tsx
  src/components/Header/HeaderContainer.tsx
  src/components/Header/HeaderView.tsx
  src/hooks/useHeader.ts
Labels: refactor

#87 feat RecipeWrite컴포넌트
  src/App.tsx
  src/hooks/useRecipeWrite.ts
  src/views/Recipes/RecipeWrite/RecipeWrite.tsx
Labels: enhancement, design

#88 vercel token 에러수정
  src/hooks/useRecipeWrite.ts
Labels: enhancement

#89 [fix]레시피작성컴포넌트 수정
  src/views/Recipes/RecipeWrite/RecipeWrite.tsx
Labels: design

#92 [refactor] 게시물작성컴포넌트명수정
  src/App.tsx
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
  src/views/Recipes/RecipeUpdate/RecipeUpdate.tsx
Labels: design

#93 [feat] search component
  src/App.tsx
  src/hooks/useSearchInput.ts
  src/hooks/useSearchRecipe.ts
  src/views/Main/Main.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Recommend/Recommend.tsx
  src/views/Recipes/SearchRecipe/SearchBox.tsx
  src/views/Recipes/SearchRecipe/SearchCondition.tsx
  src/views/Recipes/SearchRecipe/SearchContainer.tsx
  src/views/Recipes/SearchRecipe/SearchResult.tsx
  src/views/Recipes/SearchRecipe/SearchView.tsx
  src/views/Search/Search.tsx
  src/views/Signup/Signup.tsx
Labels: enhancement

#94 [feat] Search Compoment Layout
  src/App.tsx
  src/components/Header/HeaderView.tsx
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeList.tsx
  src/components/Recipe/RecipeMetaData.tsx
  src/components/Recipe/RecipePageHeader.tsx
  src/hooks/useHeaderLogic.ts
  src/hooks/useSearchRecipe.ts
  src/hooks/useUserForm.ts
  src/views/Main/Main.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/LatestRecipe/LatestRecipe.tsx
  src/views/Recipes/PopularRecipe/PopularRecipe.tsx
  src/views/Recipes/RecommendedRecipe/RecommendedRecipe.tsx
  src/views/Recipes/SearchRecipe/SearchCondition.tsx
  src/views/Recipes/SearchRecipe/SearchContainer.tsx
  src/views/Recipes/SearchRecipe/SearchResult.tsx
  src/views/Search/Search.tsx
Labels: design

#97 refactor 게시글작성페이지
  package-lock.json
  package.json
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
Labels: enhancement, design

#99 fix vercel에러 수정
  src/assets/img/defaultImg.jpeg
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
Labels: enhancement

#101 [feat] Alarm Component(SSE)
  package-lock.json
  package.json
  src/components/Alarm/Alarm.tsx
  src/components/AuthKaKao.tsx
  src/components/Header/HeaderContainer.tsx
  src/hooks/useSSE.ts
Labels: enhancement, design

#104 [fix] Login Api
  src/hooks/useUserForm.ts
Labels: bug

#105 [fix] login api - add headers
  src/hooks/useUserForm.ts
Labels: bug

#106 [feat] login - json 데이터 전송
  src/hooks/useUserForm.ts
Labels: bug

#111 [feat] Comments Api with Custom hook
  src/fakeData/reviewFake.ts
  src/hooks/useComments.ts
  src/views/Comments/CommentList.tsx
  src/views/Comments/CommentsView.tsx
  src/views/Comments/CreateComment.tsx
  src/views/Comments/Review.tsx
  src/views/Comments/ViewComments.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/PopularRecipe/PopularRecipe.tsx
Labels: enhancement

#113 [refactor] Comments Api
  src/hooks/useComments.ts
  src/views/Comments/CommentEditBtn.tsx
  src/views/Comments/CommentList.tsx
  src/views/Comments/CommentRating.tsx
  src/views/Comments/CommentsContent.tsx
  src/views/Comments/CommentsView.tsx
  src/views/Comments/CreateComment.tsx
Labels: refactor

#115 [feat] createRecipeApi
  src/hooks/useRecipeCreate.ts
  src/views/Mypage/Mypage.tsx
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
  src/views/Recipes/UpdateRecipe/UpdateRecipe.tsx
Labels: enhancement

#117 [fix] vercel에러 수정
  src/views/Mypage/Mypage.tsx
Labels: bug, enhancement

#121 [refactor] 게시물작성api 수정
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#122 [feat] Recipe api
  src/App.tsx
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeList.tsx
  src/fakeData/recipeFake.ts
  src/hooks/useSearchRecipe.ts
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/LatestRecipe/LatestRecipe.tsx
  src/views/Recipes/PopularRecipe/PopularRecipe.tsx
  src/views/Recipes/SearchRecipe/SearchContainer.tsx
  src/views/Recipes/SearchRecipe/SearchResult.tsx
Labels: enhancement

#124 [feat] kakao & login api, singup(유효성검사 api)
  src/components/AuthKaKao.tsx
  src/hooks/useUserForm.ts
  src/views/Login/SocialKakao.tsx
  src/views/Recipes/LatestRecipe/LatestRecipe.tsx
  src/views/Signup/Signup.tsx
Labels: bug, enhancement

#125 [feat] MypageAPI
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/getRecipes.ts
  src/views/Mypage/hooks/getUserInfo.ts
Labels: enhancement

#127 [fix] kakao 오타 수정
  src/App.tsx
Labels: bug

#129 [feat] updateRecipeAPI 작업
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useRecipeCreate.ts
  src/hooks/useUpdateRecipe.ts
  src/views/Mypage/Mypage.tsx
  src/views/Recipes/UpdateRecipe/UpdateRecipe.tsx
Labels: enhancement

#131 [fix] vercelError수정
  src/hooks/useGetRecipes.ts
Labels: bug

#132 [fi] Login&Signup Logic - body data 수정
  src/hooks/useUserForm.ts
  src/views/Login/SocialKakao.tsx
  src/views/Signup/Signup.tsx
Labels: bug

#133 [fix] recipeApi
  src/components/Recipe/RecipeCard.tsx
  src/hooks/useSearchRecipe.ts
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/LatestRecipe/LatestRecipe.tsx
  src/views/Recipes/PopularRecipe/PopularRecipe.tsx
Labels: bug

#134 [refactor] API 리팩토링
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useRecipeCreate.ts
  src/hooks/useUpdateRecipe.ts
Labels: enhancement

#136 [refactor] API수정
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useRecipeCreate.ts
  src/hooks/useUpdateRecipe.ts
Labels: enhancement

#137 [fix]email-check 모달창로직
  src/hooks/useUserForm.ts
  src/views/Signup/Signup.tsx
Labels: bug

#138 [fix] 레시피 무한랜더
  src/views/Recipes/LatestRecipe/LatestRecipe.tsx
  src/views/Recipes/PopularRecipe/PopularRecipe.tsx
Labels: bug

#139 [fix] 오타수정(cdoe => code)
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
Labels: bug

#140 [fix] DetailPage 예외조건 추가
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
Labels: bug

#142 [fix] token - Bearer 삭제
  src/components/AuthKaKao.tsx
  src/hooks/useUserForm.ts
Labels: bug

#143 [feat] hoc 적용
  src/App.tsx
  src/components/Header/HeaderContainer.tsx
  src/components/KaKaoButton/KaKaoLoginButton.tsx
  src/hooks/withAuth.tsx
  src/views/Main/Main.tsx
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
  src/views/Recipes/RecipeUpdate/RecipeUpdate.tsx
  src/views/Recipes/RecommendedRecipe/RecommendedRecipe.tsx
  src/views/Recipes/UpdateRecipe/UpdateRecipe.tsx
Labels: enhancement

#145 [fix] vercel error and kakao api
  src/App.tsx
  src/views/Login/SocialKakao.tsx
Labels: bug

#147 [refactor] 마이페이지컴포넌트 mui적용
  package-lock.json
  package.json
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/views/Mypage/Mypage.tsx
Labels: enhancement, design

#149 [fix] vercel에러 수정
  src/views/Mypage/Mypage.tsx
Labels: bug

#151 [feat] GuestHome
  package-lock.json
  package.json
  src/views/GuestHome/GuestHome.tsx
Labels: enhancement, design

#153 [refactor] GuestHome컴포넌트
  src/views/GuestHome/GuestHome.tsx
Labels: design

#155 [design] guesthome
  src/views/GuestHome/GuestHome.tsx
Labels: design

#157 [design] MUI 도입
  package-lock.json
  package.json
  src/App.tsx
  src/components/AuthKaKao.tsx
  src/components/Header/HeaderContainer.tsx
  src/components/Header/HeaderView.tsx
  src/components/Hero/PageHero.tsx
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeList.tsx
  src/components/Recipe/RecipeMetaData.tsx
  src/components/Recipe/RecipeNewCard.tsx
  src/components/Recipe/RecipePageHeader.tsx
  src/fakeData/recipeFake.ts
  src/hooks/useComments.ts
  src/hooks/useHeaderLogic.ts
  src/hooks/useSearchRecipe.ts
  src/hooks/useUserForm.ts
  src/styles/RecipeContainer.ts
  src/styles/colors.ts
  src/ui/Select/CustomSelect.tsx
  src/views/Home/Home.tsx
  src/views/Recipes/AllRecipes/AllRecipes.tsx
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
  src/views/Recipes/RecommendedRecipes/RecommendedRecipes.tsx
  src/views/Recipes/SearchRecipe/SearchView.tsx
  src/views/Recipes/SearchRecipes/SearchBox.tsx
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
  src/views/Recipes/SearchRecipes/SearchContainer.tsx
  src/views/Recipes/SearchRecipes/SearchResult.tsx
  src/views/Recipes/SearchRecipes/SearchViewRecipes.tsx
  src/views/Signup/Signup.tsx
Labels: bug, design

#158 [refactor] mypage수정
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/updateForm.ts
Labels: enhancement

#162 [refactor] mypage회원정보수정
  src/components/Modal/Modal.tsx
  src/hooks/useUserForm.ts
  src/utils/validation/validation.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/ usePagination.ts
  src/views/Mypage/hooks/useModal.ts
  src/views/Mypage/hooks/useUserUpdate.ts
Labels: enhancement

#163 [design] Search Component
  src/common/options.ts
  src/components/AuthKaKao.tsx
  src/components/Recipe/RecipeNewCard.tsx
  src/fakeData/recipeFake.ts
  src/styles/RecipeContainer.ts
  src/views/Recipes/SearchRecipes/SearchBox.tsx
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
  src/views/Recipes/SearchRecipes/SearchContainer.tsx
Labels: design

#165 [refactor] Login컴포넌트 디자인수정
  src/components/Modal/Modal.tsx
  src/views/Login/Login.tsx
Labels: design

#167 [fix]Search & Comments Api
  src/hooks/useComments.ts
  src/hooks/useSearchRecipe.ts
  src/views/Comments/CommentEditBtn.tsx
  src/views/Comments/CommentList.tsx
  src/views/Comments/CommentsContent.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
  src/views/Recipes/SearchRecipes/SearchContainer.tsx
  src/views/Recipes/SearchRecipes/SearchViewRecipes.tsx
Labels: bug, enhancement

#168 [fix] Vercel error
  src/views/Recipes/SearchRecipes/SearchViewRecipes.tsx
Labels: bug

#169 [design] onBoard
  src/views/Onboard/Onboard.tsx
Labels: design

#170 [fix] Comments Api create -> call fetchHandler
  src/components/Recipe/RecipeNewCard.tsx
  src/hooks/useComments.ts
  src/views/Comments/CommentEditBtn.tsx
  src/views/Comments/CommentList.tsx
Labels: bug

#174 [feat] mypage 스크랩취소,중복확인
  package-lock.json
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/ useBookmark.ts
  src/views/Mypage/hooks/ usePagination.ts
  src/views/Mypage/hooks/useModal.ts
Labels: enhancement

#177 [refactor] mypage및 전체api수정
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useRecipeCreate.ts
  src/hooks/useUpdateRecipe.ts
  src/views/Mypage/hooks/ useBookmark.ts
  src/views/Mypage/hooks/useUserUpdate.ts
Labels: enhancement

#182 [refactor] mypageAPI
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
Labels: enhancement

#184 [feat] Redux-toolkit 도입
  src/hooks/useComments.ts
  src/views/Comments/CommentEditBtn.tsx
Labels: enhancement

#185 [fix] 커스텀 훅 공백삭제(useBookmark, usePagenation)
  package-lock.json
  package.json
  src/main.tsx
  src/redux/reducer/rootReducer.ts
  src/redux/reducer/userSlice.ts
  src/redux/store/store.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/useBookmark.ts
  src/views/Mypage/hooks/usePagination2.ts
Labels: bug

#186 [feat] Redux-toolkit 도입 및 useReducer 적용
  package-lock.json
  package.json
  src/components/AuthKaKao.tsx
  src/components/Header/HeaderContainer.tsx
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeNewCard.tsx
  src/hooks/useAuthToken.ts
  src/hooks/useComments.ts
  src/hooks/useHeaderLogic.ts
  src/hooks/useSearchRecipe.ts
  src/hooks/useUserForm.ts
  src/hooks/withAuth.tsx
  src/main.tsx
  src/redux/reducer/rootReducer.ts
  src/redux/reducer/userSlice.ts
  src/redux/store/store.ts
  src/views/Comments/CommentEditBtn.tsx
Labels: enhancement

#187 [fix] Update comment handler
  src/hooks/useComments.ts
  src/views/Comments/CreateComment.tsx
Labels: bug

#190 [fix] Comment Api(update 오타수정) 및 status 추가
  src/hooks/useAuthToken.ts
  src/hooks/useComments.ts
Labels: bug

#192 [refactor] 게시물작성레시피
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#194 [refactor] api response확인
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#196 [refactor] api
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#198 [refactor] formData json객체로수정
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#199 [feat] Scrap Recipe - 삭제 기능 추가
  src/components/Recipe/RecipeNewCard.tsx
  src/hooks/useComments.ts
Labels: enhancement

#204 [refactor] 마이페이지수정
  src/components/Modal/Modal.tsx
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/utils/validation/validation.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/updateForm.ts
  src/views/Mypage/hooks/useUserUpdate.ts
Labels: enhancement, design

#206 [refactor] mypage 비밀번호확인추가
  src/utils/validation/validation.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/updateForm.ts
  src/views/Mypage/hooks/useModal.ts
Labels: enhancement, design

#208 [refactor] mypage
  src/views/Mypage/Mypage.tsx
Labels: enhancement

#211 [feat] accessToken interceptor 요청시간 삭제
  src/utils/api/instance.ts
Labels: bug, enhancement

#212 [refactor] 게시글api,비밀번호확인api
  package-lock.json
  package.json
  src/hooks/useGetMyRecipes.ts
  src/views/Mypage/Mypage.tsx
Labels: enhancement

#213 [fix] interceptor - add Content-Type(in headers)
  src/utils/api/instance.ts
Labels: bug

#215 Fix: accessToken interceptor - headers의 access-token설정
  src/utils/api/instance.ts
Labels: bug

#217 [fix] interceptor headers 수정
  src/hooks/useSSE.ts
  src/utils/api/instance.ts
Labels: bug

#218 [refactor] api수정
  src/hooks/useGetMyRecipes.ts
Labels: enhancement

#221 Refactor/#219/api
  src/hooks/useGetMyRecipes.ts
Labels: enhancement

#222 [refactor] 페이징처리수정
  src/hooks/useGetMyRecipes.ts
Labels: enhancement

#223 [fix] refreshToken handler
  src/utils/api/reissueToken.ts
Labels: bug

#224 [refactor] 에러메세지수정
  src/views/Mypage/Mypage.tsx
Labels: enhancement

#228 [refactor] 회원가입버튼
  src/views/Signup/Signup.tsx
Labels: enhancement

#229 [refactor] 이메일중복api
  src/views/Signup/Signup.tsx
Labels: enhancement

#231 [refactor] 이메일중복
  src/views/Signup/Signup.tsx
Labels: enhancement

#232 [fix] interceptor - 로그인 테스트(err.response 확인)
  src/utils/api/instance.ts
  src/utils/api/reissueToken.ts
Labels: bug

#234 [refactor] 마이페이지,게시물등록페이지
  src/hooks/useRecipeCreate.ts
  src/views/Recipes/UpdateRecipe/UpdateRecipe.tsx
Labels: enhancement

#235 [feat] interceptor 로직 적용
  src/components/AuthKaKao.tsx
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeNewCard.tsx
  src/hooks/useComments.ts
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/hooks/useRecipeCreate.ts
  src/hooks/useSearchInput.ts
  src/hooks/useSearchRecipe.ts
  src/hooks/useUpdateRecipe.ts
  src/utils/api/instance.ts
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/useBookmark.ts
  src/views/Mypage/hooks/useUserUpdate.ts
  src/views/Recipes/AllRecipes/AllRecipes.tsx
  src/views/Recipes/DetailRecipe/DetailRecipe.tsx
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
  src/views/Recipes/RecommendedRecipes/RecommendedRecipes.tsx
Labels: enhancement

#236 [fix] interceptor logic - delete unused
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeNewCard.tsx
  src/hooks/useGetMyRecipes.ts
  src/hooks/useGetUserInfo.ts
  src/utils/api/reissueToken.ts
  src/views/Mypage/hooks/useUserUpdate.ts
Labels: bug

#237 [fix] accessToken refresh logic- 기존토큰 추가하여 요청
  src/utils/api/reissueToken.ts
Labels: bug

#238 [fix] refresh token 만료시 store logout
  src/utils/api/instance.ts
  src/utils/api/reissueToken.ts
Labels: bug

#240 [refactor] signup
  src/views/Signup/Signup.tsx
Labels: enhancement

#241 [refactor] 회원가입
  src/views/Signup/Signup.tsx
Labels: enhancement

#242 [refactor] check핸들러수정
  src/views/Signup/Signup.tsx
Labels: enhancement

#244 [refactor] 회원가입유효성검사
  src/utils/validation/validation.ts
  src/views/Signup/Signup.tsx
Labels: enhancement

#245 [refactor] 회원가입로직
  src/hooks/useUserForm.ts
  src/utils/validation/validation.ts
Labels: enhancement

#247 [refactor] 회원정보수정
  src/views/Mypage/Mypage.tsx
  src/views/Mypage/hooks/useUserUpdate.ts
Labels: enhancement

#250 [design] guesthome
  src/views/GuestHome/GuestHome.tsx
Labels: enhancement

#253 [feat] Popular Component 무한스크롤 도입
  src/hooks/useObserver.ts
  src/redux/store/store.ts
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
Labels: enhancement

#254 [feat]무한스크롤 - 전체 적용
  src/components/Recipe/RecipeNewCard.tsx
  src/fakeData/recipeFake.ts
  src/hooks/useSSE.ts
  src/hooks/useSearchRecipe.ts
  src/views/Recipes/AllRecipes/AllRecipes.tsx
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
Labels: enhancement

#256 [fix] infinite scroll - offset확인
  package-lock.json
  package.json
  src/views/Recipes/AllRecipes/AllRecipes.tsx
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
Labels: bug

#257 [fix] Infinite scroll - 초기 데이터 가져오기
  src/hooks/useObserver.ts
  src/views/Recipes/AllRecipes/AllRecipes.tsx
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
Labels: bug

#259 [fix] vercel error
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
Labels: bug

#260 [fix] vercel error -popular recipes props
  src/App.tsx
  src/views/Home/Home.tsx
  src/views/Recipes/PopularRecipes/PopularRecipeData.tsx
  src/views/Recipes/PopularRecipes/PopularRecipes.tsx
  src/views/Recipes/PopularRecipes/PopularRecipesView.tsx
  src/views/Recipes/SearchRecipes/SearchContainer.tsx
Labels: bug

#252 [refactor] 레시피등록 api
  src/hooks/useRecipeCreate.ts
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
Labels: enhancement, design

#262 [refactor] createRecipe
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#264 [refactor] submit버튼수정
  src/hooks/useRecipeCreate.ts
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
Labels: enhancement

#266 [refactor] thumbnail api수정
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#269 [refactor] 닉네임중복확인 메세지오류 수정
  src/views/Signup/Signup.tsx
Labels: enhancement

#271 [refactor] 레시피등록관련 api 수정
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#272 [feat] commonModal 적용
  src/handler/userFormHandler.ts
  src/hooks/useComments.ts
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
  src/views/Recipes/SearchRecipes/SearchContainer.tsx
  src/views/Recipes/SearchRecipes/SearchViewRecipes.tsx
Labels: enhancement

#274 [fix] commonModal - 함수 로직 추가
  src/components/Modal/Globalmodal.tsx
  src/handler/userFormHandler.ts
  src/hooks/useComments.ts
  src/redux/reducer/modalSlice.ts
  src/views/Login/Login.tsx
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
Labels: enhancement

#276 [refactor] 레시피명 유효성검사추가
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#284 [refactor] 게시물등록록api
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#285 [fix] fetchRecipes - new Promise 반환
  src/utils/api/instance.ts
Labels: bug

#287 [fix] 레시피등록api
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#288 [fix] recipesCreate
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#289 [fix] null token response check
  src/utils/api/instance.ts
Labels: bug

#290 [fix] 썸네일api수정
  src/hooks/useRecipeCreate.ts
  src/views/Recipes/CreateRecipe/CreateRecipe.tsx
Labels: enhancement

#292 [fix] null Token logic
  src/utils/api/instance.ts
Labels: bug

#293 [fix] 조리단계api 앤드포인트수정
  src/hooks/useRecipeCreate.ts
Labels: bug

#296 [fix] 레시피등록
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#297 [fix] 삭제api & 작성게시글Link to
  src/hooks/useRecipeCreate.ts
  src/hooks/useRecipeDelete.ts
  src/views/Mypage/Mypage.tsx
Labels: enhancement

#299 [refactor] 삭제api
  src/hooks/useGetMyRecipes.ts
  src/hooks/useRecipeDelete.ts
  src/views/Mypage/Mypage.tsx
Labels: enhancement

#303 [design] Headers Contents
  src/components/Header/HeaderContainer.tsx
  src/components/Recipe/RecipeCard.tsx
  src/components/Recipe/RecipeNewCard.tsx
  src/hooks/useHeaderLogic.ts
Labels: design

#307 [refactor] updateRecipe
  src/hooks/useUpdateRecipe.ts
  src/views/Recipes/UpdateRecipe/UpdateRecipe.tsx
Labels: enhancement

#309 [fix] searchApi - api endpoint 수정
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
Labels: bug

#311 [fix] console확인
  src/hooks/useRecipeCreate.ts
  src/hooks/useUpdateRecipe.ts
Labels: bug

#312 [refactor] vercelError
  src/hooks/useRecipeCreate.ts
Labels: enhancement

#313 [refactor] 오타수정
  src/hooks/useUpdateRecipe.ts
Labels: enhancement

#314 [refactor] 상태저장하는 로직변경
  src/hooks/useRecipeCreate.ts
  src/hooks/useUpdateRecipe.ts
  src/views/Recipes/UpdateRecipe/UpdateRecipe.tsx
Labels: enhancement

#315 [fix] Search api
  src/views/Recipes/PopularRecipes/PopularRecipeData.tsx
  src/views/Recipes/SearchRecipes/SearchCondition.tsx
  src/views/Recipes/SearchRecipes/SearchContainer.tsx
  src/views/Recipes/SearchRecipes/SearchResult.tsx
  src/views/Recipes/SearchRecipes/SearchViewRecipes.tsx
Labels: bug, enhancement

#317 [refactor] 오타수정
  src/hooks/useUpdateRecipe.ts
Labels: enhancement
