Repository JaManChu/frontend, pull requests merged in 2024-09, with the labels that each got.

#4 이슈테스트
  README.md
Labels: enhancement

#5 이슈테스트
  README.md
Labels: enhancement

#7 feat/#6/이슈생성테스트
  README.md
Labels: enhancement

#8 [feat] React Setting
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#10 [chore] Project Structure
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
Labels: enhancement

#15 Design/#11/onboard
  index.html
  package-lock.json
  package.json
  src/App.css
  src/main.tsx
  src/views/guestHome.tsx
  src/views/login.tsx
  src/views/mypage.tsx
  src/views/onboard.tsx
  src/views/signup.tsx
Labels: design

#19 Design/#16/signup
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/styles/layout.tsx
  src/views/guestHome.tsx
  src/views/onboard.tsx
  src/views/signup.tsx
Labels: enhancement, design

#20 [design] Header Compoment
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Header/Header.tsx
  src/styles/App.css
Labels: enhancement, design

#23 chore/#22/컴포넌트명수정
  src/App.tsx
  src/views/GuestHome/GuestHome.tsx
  src/views/Login/Login.tsx
  src/views/Mypage/Mypage.tsx
  src/views/Onboard/Onboard.tsx
  src/views/Signup/Signup.tsx
Labels: enhancement

#25 [feat] 회원가입유효성
  src/App.tsx
  src/components/Modal.tsx
  src/views/Signup/Signup.tsx
Labels: enhancement

#26 [feat] MainPageComponent(for User)
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header/Header.tsx
  src/main.tsx
  src/views/Main/Main.tsx
  src/views/Onboard/Onboard.tsx
  src/views/Recipes/Latest/Latest.tsx
  src/views/Recipes/Popular/Popular.tsx
  src/views/Recipes/Recommend/Recommend.tsx
Labels: enhancement, design

#31 [feat] Login component
  src/components/KaKaoButton/KaKaoLoginButton.tsx
  src/components/Modal/Modal.tsx
  src/views/Login/Login.tsx
  src/views/Onboard/Onboard.tsx
  src/views/Signup/Signup.tsx
Labels: enhancement
